apiVersion: v1
kind: Service
metadata:
  name: classification-service
  namespace: ml-apis
spec:
  type: NodePort
  selector:
    app: classification-api
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30002
    protocol: TCP