apiVersion: apps/v1
kind: Deployment
metadata:
  name: classification-api
  namespace: ml-apis
  labels:
    app: classification-api
spec:
  replicas: 1  # 1 pods
  selector:
    matchLabels:
      app: classification-api
  template:
    metadata:
      labels:
        app: classification-api
    spec:
      containers:
      - name: classification-api
        image: classification-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MODEL_PATH
          value: "model/classification_model.onnx"
        resources:
          requests:
            cpu: "0.05"
            memory: "64Mi"
          limits:
            cpu: "0.1"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5