apiVersion: v1
kind: Service
metadata:
  name: regression-service
  namespace: ml-apis
spec:
  type: NodePort
  selector:
    app: regression-api
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001
    protocol: TCP